name: peminjam_perpustakaan_kelas_b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.0 # library untuk http connection
  pretty_dio_logger: ^1.3.1 # logging  http
  get_storage: ^2.1.1 # untuk session/local storage
  flutter: 
    sdk: flutter

  flutter_native_splash: 2.3.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/

